name: OnlineRewards
main: org.example.onlinerewards.OnlineRewardsPlugin
version: 1.0-SNAPSHOT
api-version: '1.20'
commands:
  onlinerewards:
    description: Reload OnlineRewards configuration
    usage: /<command> reload
    permission: onlinerewards.reload
    aliases: [or]
permissions:
  onlinerewards.reload:
    description: Allows reloading the plugin configuration
    default: op
